### PR TITLE
fix: Various style fixes. 💅🏻

### PR DESCRIPTION
**Pull request by bwinton**
Add a border to the sidebar to distinguish it from page content.
Make the background colour of the active tab match the spec.
Add a border and box shadow to the meta image.
Show the dashed border image on missing images.
Add some padding.
Move the favicon down to the bottom of the thumbnail.
Only show the hostname for http(s) urls.

Reviewer: @ericawright

### CODE REVIEW

**Comment by Keith94** [comment]
https://github.com/bwinton/VerticalTabs/blob/0e3a443384424b0e756912b1c1b0bf93e868dd1f/skin/base.css#L567

The padding makes the favicons look too blurry so I think it should be changed to 3px rather than 2px.

Also the white background color can be removed from favicons when not in "large tabs mode".

**Comment by bwinton** [comment]
Good call on both comments!  I fixed the white background colour in small tabs mode, but I think 3px is a little big, so I shrank the size a little to keep it at 2px while remaining crisp.

**Comment by Keith94** [comment]
Thanks. Another thing, the tabs box is missing a border when unpinned (and window is maximized), but when restored there seems to be a transparent border on the right of it (Windows 8). Can you check that?

**Comment by bwinton** [comment]
I don't have Windows 8 (only 7 and 10 in virtual machines)…  Could you post a screenshot?

**Comment by Keith94** [comment]
In maximized window (no visible border on sidebar):

snag 2016 07 22 19 56 43

Restored window (1px border):
snag 2016 07 22 19 56 20

I could open a new issue.

**Comment by bwinton** [comment]
Huh, weird.  I'll see if I can fix that in this patch, so that I don't forget about it.  (Probably Monday, though. 🙂)

**Comment by bwinton** [comment]
Splitter border fixed.

**Comment by ericawright** [comment]
*Win 8*
screen shot 2016-07-25 at 10 57 00 am
full screen unpinned ^ 👍 

screen shot 2016-07-25 at 10 56 36 am
full screen pinned ^ (is the splitter too large?)

screen shot 2016-07-25 at 10 56 19 am
pinned not full screen ^ 

screen shot 2016-07-25 at 10 55 30 am
unpinned not full screen ^ still sees a little of the background through it. Due to `#browser-border-start` should we change this?

**Comment by bwinton** [comment]
I don't _think_ the splitter is too large, but I wonder if we should force the `#browser-border-start` to `display:none`…  Can you whip up some screenshots of that with the Browser Toolbox and post them?

**Comment by ericawright** [comment]
screen shot 2016-07-25 at 11 23 05 am
screen shot 2016-07-25 at 11 22 50 am
screen shot 2016-07-25 at 11 21 32 am
screen shot 2016-07-25 at 11 23 46 am

**Pull request merged**
