### PR TITLE
fix: Make the collapsed-width a little bigger. 🖼

### PR DESCRIPTION
**Pull request by bwinton**
Move the collapsed width to a variable so we can more easily change it.
Make it `60px` instead of `45px` to show the entire thumbnail.

Reviewer: @ericawright.

### CODE REVIEW

**Comment by ericawright** [comment]
since it's a css var now, could we make it a pref? (that may lead down a long never-ending road)

**Comment by bwinton** [comment]
We could.  I don't think I'ld want to for something this small, though…

**Comment by bwinton** [comment]
Okay, fine, it's back to `45px`.  But I think the rest of the changes are probably still worth merging…  😉

**Comment by ericawright** [comment]
lol, okay :)

**Pull request merged**
