### PR TITLE
fix: Make the pinned sidebar resizable.  ⟸║⟹   😃

### LINKED ISSUE #23: Allow resizing the side bar when pinned

### PR DESCRIPTION
**Pull request by bwinton**
Update stylelint to match the version in my editor.
Switch the width of the sidebar to use a css variable.
Add a splitter box, and adjust the css variable when it's moved.

Fixes #23.
Reviewed by @ericawright.

### CODE REVIEW

**Comment by johngruen** [comment]
@bwinton whooooooooaaaaaahhhhh

**Comment by ericawright** [comment]
screen shot 2016-06-28 at 5 29 28 pm
What should we do about that pin button at smaller sizes?
vertical align?

**Comment by ericawright** [comment]
screen shot 2016-06-30 at 11 06 51 am

**Comment by bwinton** [comment]
Yeah, I think I'm okay with that crop…  I mean, it's not perfect, but close enough, right?  ;)

**Comment by johngruen** [comment]
woot

**Pull request merged**
